# Makefile.in generated by automake 1.11.3 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011 Free Software
# Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.





pkgdatadir = $(datadir)/fastc
pkgincludedir = $(includedir)/fastc
pkglibdir = $(libdir)/fastc
pkglibexecdir = $(libexecdir)/fastc
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = fastc$(EXEEXT)
subdir = .
DIST_COMMON = $(am__configure_deps) $(dist_noinst_SCRIPTS) \
	$(srcdir)/Makefile.am $(srcdir)/Makefile.in \
	$(top_srcdir)/configure build-aux/depcomp build-aux/install-sh \
	build-aux/missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am__dirstamp = $(am__leading_dot)dirstamp
am_fastc_OBJECTS = src/main.$(OBJEXT) src/Kernel.$(OBJEXT) \
	src/Design.$(OBJEXT) src/utils.$(OBJEXT) \
	src/AstToDfgVisitor.$(OBJEXT) src/AstToMaxJVisitor.$(OBJEXT) \
	src/StencilAstToMaxJVisitor.$(OBJEXT) \
	src/DotDFSVisitor.$(OBJEXT) src/DotPrint.$(OBJEXT) \
	src/DfeTask.$(OBJEXT) src/DfeGraph.$(OBJEXT) \
	src/Stencil.$(OBJEXT) src/StencilCodeGenerator.$(OBJEXT) \
	src/StencilOffset.$(OBJEXT) \
	src/DataFlowGraph/DataFlowGraph.$(OBJEXT) \
	src/DataFlowGraph/InputNode.$(OBJEXT) \
	src/DataFlowGraph/OutputNode.$(OBJEXT) \
	src/DataFlowGraph/Node.$(OBJEXT) \
	src/DataFlowGraph/SinkNode.$(OBJEXT) \
	src/DataFlowGraph/SourceNode.$(OBJEXT) \
	src/DataFlowGraph/MuxNode.$(OBJEXT) \
	src/DataFlowGraph/DFSVisitor.$(OBJEXT) \
	src/DataFlowGraph/BFSVisitor.$(OBJEXT) \
	src/DataFlowGraph/TopSortVisitor.$(OBJEXT) \
	src/DataFlowGraph/CounterNode.$(OBJEXT) \
	src/passes/GenerateAnalysisOverview.$(OBJEXT) \
	src/passes/KernelVisitor.$(OBJEXT) \
	src/passes/CodeGeneration.$(OBJEXT) \
	src/passes/KernelExtraction.$(OBJEXT) \
	src/passes/TaskExtraction.$(OBJEXT) \
	src/passes/BuildDFG.$(OBJEXT) src/passes/PrintDotDFG.$(OBJEXT) \
	src/passes/ExtractStencil.$(OBJEXT) \
	src/passes/MergeKernels.$(OBJEXT) \
	src/highlevel/HLAVisitor.$(OBJEXT) \
	src/highlevel/HighlevelAnalysis.$(OBJEXT) \
	src/ife/IFEVisitor.$(OBJEXT) src/DfeTopSortVisitor.$(OBJEXT) \
	src/ife/IdlefunctionElimination.$(OBJEXT)
fastc_OBJECTS = $(am_fastc_OBJECTS)
fastc_LDADD = $(LDADD)
SCRIPTS = $(dist_noinst_SCRIPTS)
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/build-aux/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
SOURCES = $(fastc_SOURCES)
DIST_SOURCES = $(fastc_SOURCES)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/paul-g/workspaces/phd/projects/fastcc/build-aux/missing --run aclocal-1.11
AMTAR = $${TAR-tar}
AM_CXXFLAGS =  -I/opt/rose/0.9.5/include -I/opt/boost/1.47/include -Winvalid-pch -g3 -O0
AM_LDFLAGS =  -L/opt/rose/0.9.5/lib -L/opt/boost/1.47/lib
AUTOCONF = ${SHELL} /home/paul-g/workspaces/phd/projects/fastcc/build-aux/missing --run autoconf
AUTOHEADER = ${SHELL} /home/paul-g/workspaces/phd/projects/fastcc/build-aux/missing --run autoheader
AUTOMAKE = ${SHELL} /home/paul-g/workspaces/phd/projects/fastcc/build-aux/missing --run automake-1.11
AWK = gawk
CPPFLAGS = 
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"FAST\ Compiler\" -DPACKAGE_TARNAME=\"fastc\" -DPACKAGE_VERSION=\"0.1\" -DPACKAGE_STRING=\"FAST\ Compiler\ 0.1\" -DPACKAGE_BUGREPORT=\"paul.grigoras90@gmail.com\" -DPACKAGE_URL=\"https://github.com/paul-g/fastc\"
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EXEEXT = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = -lboost_regex -lboost_filesystem -lboost_system -lrose 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/paul-g/workspaces/phd/projects/fastcc/build-aux/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
OBJEXT = o
PACKAGE = fastc
PACKAGE_BUGREPORT = paul.grigoras90@gmail.com
PACKAGE_NAME = FAST Compiler
PACKAGE_STRING = FAST Compiler 0.1
PACKAGE_TARNAME = fastc
PACKAGE_URL = https://github.com/paul-g/fastc
PACKAGE_VERSION = 0.1
PATH_SEPARATOR = :
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
VERSION = 0.1
abs_builddir = /home/paul-g/workspaces/phd/projects/fastcc
abs_srcdir = /home/paul-g/workspaces/phd/projects/fastcc
abs_top_builddir = /home/paul-g/workspaces/phd/projects/fastcc
abs_top_srcdir = /home/paul-g/workspaces/phd/projects/fastcc
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/paul-g/workspaces/phd/projects/fastcc/build-aux/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = subdir-objects
ACLOCAL_AMFLAGS = ${ACLOCAL_FLAGS}
fastc_SOURCES = src/main.cxx src/main.hxx \
  src/Kernel.hxx src/Kernel.cxx \
  src/Design.hxx src/Design.cxx \
  src/Compiler.hxx \
  src/precompiled.hxx src/utils.hxx src/utils.cxx \
  src/AstToDfgVisitor.hxx src/AstToDfgVisitor.cxx \
  src/AstToMaxJVisitor.hxx src/AstToMaxJVisitor.cxx \
  src/StencilAstToMaxJVisitor.hxx src/StencilAstToMaxJVisitor.cxx \
  src/DotDFSVisitor.hxx src/DotDFSVisitor.cxx \
  src/DotPrint.hxx src/DotPrint.cxx\
  src/DfeTask.hxx src/DfeTask.cxx \
  src/DfeGraph.hxx src/DfeGraph.cxx \
  src/Stencil.h src/Stencil.cc \
  src/StencilCodeGenerator.h src/StencilCodeGenerator.cc \
  src/StencilOffset.h src/StencilOffset.cc \
  src/DataFlowGraph/DataFlowGraph.hxx src/DataFlowGraph/DataFlowGraph.cxx \
  src/DataFlowGraph/InputNode.hxx src/DataFlowGraph/InputNode.cxx  \
  src/DataFlowGraph/OutputNode.hxx src/DataFlowGraph/OutputNode.cxx \
  src/DataFlowGraph/Node.hxx src/DataFlowGraph/Node.cxx \
  src/DataFlowGraph/SinkNode.hxx src/DataFlowGraph/SinkNode.cxx \
  src/DataFlowGraph/SourceNode.hxx src/DataFlowGraph/SourceNode.cxx \
  src/DataFlowGraph/MuxNode.hxx src/DataFlowGraph/MuxNode.cxx\
  src/DataFlowGraph/DFSVisitor.hxx src/DataFlowGraph/DFSVisitor.cxx \
  src/DataFlowGraph/BFSVisitor.hxx src/DataFlowGraph/BFSVisitor.cxx \
  src/DataFlowGraph/TopSortVisitor.hxx src/DataFlowGraph/TopSortVisitor.cxx \
  src/DataFlowGraph/CounterNode.hxx src/DataFlowGraph/CounterNode.cxx\
  src/passes/ExtractOutputs.hxx \
  src/passes/GenerateAnalysisOverview.h src/passes/GenerateAnalysisOverview.cc \
  src/passes/ManagerExtraction.hxx \
  src/passes/RemoveFast.hxx src/passes/Pass.hxx \
  src/passes/KernelVisitor.hxx src/passes/KernelVisitor.cxx \
  src/passes/CodeGeneration.hxx src/passes/CodeGeneration.cxx \
  src/passes/KernelExtraction.hxx src/passes/KernelExtraction.cxx \
  src/passes/TaskExtraction.hxx src/passes/TaskExtraction.cxx \
  src/passes/HostCodeGeneration.hxx \
  src/passes/PragmaExtraction.hxx \
  src/passes/InlineKernels.hxx \
  src/passes/ExtractDesignConstants.hxx \
  src/passes/InputOutputExtraction.hxx \
  src/passes/BuildDFG.hxx src/passes/BuildDFG.cxx \
  src/passes/PrintDotDFG.hxx src/passes/PrintDotDFG.cxx \
  src/passes/ExtractStencil.h src/passes/ExtractStencil.cc \
  src/passes/MergeKernels.h src/passes/MergeKernels.cc \
  src/highlevel/HLAVisitor.hxx src/highlevel/HLAVisitor.cxx \
  src/highlevel/HighlevelAnalysis.hxx src/highlevel/HighlevelAnalysis.cxx \
  src/ife/IFEVisitor.hxx src/ife/IFEVisitor.cxx \
  src/ife/Segment.h src/ife/Configuration.h src/ife/Partition.h \
  src/DfeTopSortVisitor.hxx src/DfeTopSortVisitor.cxx \
  src/ife/IdlefunctionElimination.hxx src/ife/IdlefunctionElimination.cxx


#BUILT_SOURCES = src/precompiled.hxx.gch
#src/precompiled.hxx.gch: src/precompiled.hxx
#	$(CXXCOMPILE) -c $<
dist_noinst_SCRIPTS = autogen.sh tests.sh clean.sh
EXTRA_DIST = test/ scripts doc example aspects demos include
all: all-am

.SUFFIXES:
.SUFFIXES: .cc .cxx .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: > src/$(am__dirstamp)
src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/$(DEPDIR)
	@: > src/$(DEPDIR)/$(am__dirstamp)
src/main.$(OBJEXT): src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/Kernel.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/Design.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/utils.$(OBJEXT): src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/AstToDfgVisitor.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/AstToMaxJVisitor.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/StencilAstToMaxJVisitor.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/DotDFSVisitor.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/DotPrint.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/DfeTask.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/DfeGraph.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/Stencil.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/StencilCodeGenerator.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/StencilOffset.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/DataFlowGraph/$(am__dirstamp):
	@$(MKDIR_P) src/DataFlowGraph
	@: > src/DataFlowGraph/$(am__dirstamp)
src/DataFlowGraph/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/DataFlowGraph/$(DEPDIR)
	@: > src/DataFlowGraph/$(DEPDIR)/$(am__dirstamp)
src/DataFlowGraph/DataFlowGraph.$(OBJEXT):  \
	src/DataFlowGraph/$(am__dirstamp) \
	src/DataFlowGraph/$(DEPDIR)/$(am__dirstamp)
src/DataFlowGraph/InputNode.$(OBJEXT):  \
	src/DataFlowGraph/$(am__dirstamp) \
	src/DataFlowGraph/$(DEPDIR)/$(am__dirstamp)
src/DataFlowGraph/OutputNode.$(OBJEXT):  \
	src/DataFlowGraph/$(am__dirstamp) \
	src/DataFlowGraph/$(DEPDIR)/$(am__dirstamp)
src/DataFlowGraph/Node.$(OBJEXT): src/DataFlowGraph/$(am__dirstamp) \
	src/DataFlowGraph/$(DEPDIR)/$(am__dirstamp)
src/DataFlowGraph/SinkNode.$(OBJEXT):  \
	src/DataFlowGraph/$(am__dirstamp) \
	src/DataFlowGraph/$(DEPDIR)/$(am__dirstamp)
src/DataFlowGraph/SourceNode.$(OBJEXT):  \
	src/DataFlowGraph/$(am__dirstamp) \
	src/DataFlowGraph/$(DEPDIR)/$(am__dirstamp)
src/DataFlowGraph/MuxNode.$(OBJEXT):  \
	src/DataFlowGraph/$(am__dirstamp) \
	src/DataFlowGraph/$(DEPDIR)/$(am__dirstamp)
src/DataFlowGraph/DFSVisitor.$(OBJEXT):  \
	src/DataFlowGraph/$(am__dirstamp) \
	src/DataFlowGraph/$(DEPDIR)/$(am__dirstamp)
src/DataFlowGraph/BFSVisitor.$(OBJEXT):  \
	src/DataFlowGraph/$(am__dirstamp) \
	src/DataFlowGraph/$(DEPDIR)/$(am__dirstamp)
src/DataFlowGraph/TopSortVisitor.$(OBJEXT):  \
	src/DataFlowGraph/$(am__dirstamp) \
	src/DataFlowGraph/$(DEPDIR)/$(am__dirstamp)
src/DataFlowGraph/CounterNode.$(OBJEXT):  \
	src/DataFlowGraph/$(am__dirstamp) \
	src/DataFlowGraph/$(DEPDIR)/$(am__dirstamp)
src/passes/$(am__dirstamp):
	@$(MKDIR_P) src/passes
	@: > src/passes/$(am__dirstamp)
src/passes/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/passes/$(DEPDIR)
	@: > src/passes/$(DEPDIR)/$(am__dirstamp)
src/passes/GenerateAnalysisOverview.$(OBJEXT):  \
	src/passes/$(am__dirstamp) \
	src/passes/$(DEPDIR)/$(am__dirstamp)
src/passes/KernelVisitor.$(OBJEXT): src/passes/$(am__dirstamp) \
	src/passes/$(DEPDIR)/$(am__dirstamp)
src/passes/CodeGeneration.$(OBJEXT): src/passes/$(am__dirstamp) \
	src/passes/$(DEPDIR)/$(am__dirstamp)
src/passes/KernelExtraction.$(OBJEXT): src/passes/$(am__dirstamp) \
	src/passes/$(DEPDIR)/$(am__dirstamp)
src/passes/TaskExtraction.$(OBJEXT): src/passes/$(am__dirstamp) \
	src/passes/$(DEPDIR)/$(am__dirstamp)
src/passes/BuildDFG.$(OBJEXT): src/passes/$(am__dirstamp) \
	src/passes/$(DEPDIR)/$(am__dirstamp)
src/passes/PrintDotDFG.$(OBJEXT): src/passes/$(am__dirstamp) \
	src/passes/$(DEPDIR)/$(am__dirstamp)
src/passes/ExtractStencil.$(OBJEXT): src/passes/$(am__dirstamp) \
	src/passes/$(DEPDIR)/$(am__dirstamp)
src/passes/MergeKernels.$(OBJEXT): src/passes/$(am__dirstamp) \
	src/passes/$(DEPDIR)/$(am__dirstamp)
src/highlevel/$(am__dirstamp):
	@$(MKDIR_P) src/highlevel
	@: > src/highlevel/$(am__dirstamp)
src/highlevel/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/highlevel/$(DEPDIR)
	@: > src/highlevel/$(DEPDIR)/$(am__dirstamp)
src/highlevel/HLAVisitor.$(OBJEXT): src/highlevel/$(am__dirstamp) \
	src/highlevel/$(DEPDIR)/$(am__dirstamp)
src/highlevel/HighlevelAnalysis.$(OBJEXT):  \
	src/highlevel/$(am__dirstamp) \
	src/highlevel/$(DEPDIR)/$(am__dirstamp)
src/ife/$(am__dirstamp):
	@$(MKDIR_P) src/ife
	@: > src/ife/$(am__dirstamp)
src/ife/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/ife/$(DEPDIR)
	@: > src/ife/$(DEPDIR)/$(am__dirstamp)
src/ife/IFEVisitor.$(OBJEXT): src/ife/$(am__dirstamp) \
	src/ife/$(DEPDIR)/$(am__dirstamp)
src/DfeTopSortVisitor.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/ife/IdlefunctionElimination.$(OBJEXT): src/ife/$(am__dirstamp) \
	src/ife/$(DEPDIR)/$(am__dirstamp)
fastc$(EXEEXT): $(fastc_OBJECTS) $(fastc_DEPENDENCIES) $(EXTRA_fastc_DEPENDENCIES) 
	@rm -f fastc$(EXEEXT)
	$(CXXLINK) $(fastc_OBJECTS) $(fastc_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f src/AstToDfgVisitor.$(OBJEXT)
	-rm -f src/AstToMaxJVisitor.$(OBJEXT)
	-rm -f src/DataFlowGraph/BFSVisitor.$(OBJEXT)
	-rm -f src/DataFlowGraph/CounterNode.$(OBJEXT)
	-rm -f src/DataFlowGraph/DFSVisitor.$(OBJEXT)
	-rm -f src/DataFlowGraph/DataFlowGraph.$(OBJEXT)
	-rm -f src/DataFlowGraph/InputNode.$(OBJEXT)
	-rm -f src/DataFlowGraph/MuxNode.$(OBJEXT)
	-rm -f src/DataFlowGraph/Node.$(OBJEXT)
	-rm -f src/DataFlowGraph/OutputNode.$(OBJEXT)
	-rm -f src/DataFlowGraph/SinkNode.$(OBJEXT)
	-rm -f src/DataFlowGraph/SourceNode.$(OBJEXT)
	-rm -f src/DataFlowGraph/TopSortVisitor.$(OBJEXT)
	-rm -f src/Design.$(OBJEXT)
	-rm -f src/DfeGraph.$(OBJEXT)
	-rm -f src/DfeTask.$(OBJEXT)
	-rm -f src/DfeTopSortVisitor.$(OBJEXT)
	-rm -f src/DotDFSVisitor.$(OBJEXT)
	-rm -f src/DotPrint.$(OBJEXT)
	-rm -f src/Kernel.$(OBJEXT)
	-rm -f src/Stencil.$(OBJEXT)
	-rm -f src/StencilAstToMaxJVisitor.$(OBJEXT)
	-rm -f src/StencilCodeGenerator.$(OBJEXT)
	-rm -f src/StencilOffset.$(OBJEXT)
	-rm -f src/highlevel/HLAVisitor.$(OBJEXT)
	-rm -f src/highlevel/HighlevelAnalysis.$(OBJEXT)
	-rm -f src/ife/IFEVisitor.$(OBJEXT)
	-rm -f src/ife/IdlefunctionElimination.$(OBJEXT)
	-rm -f src/main.$(OBJEXT)
	-rm -f src/passes/BuildDFG.$(OBJEXT)
	-rm -f src/passes/CodeGeneration.$(OBJEXT)
	-rm -f src/passes/ExtractStencil.$(OBJEXT)
	-rm -f src/passes/GenerateAnalysisOverview.$(OBJEXT)
	-rm -f src/passes/KernelExtraction.$(OBJEXT)
	-rm -f src/passes/KernelVisitor.$(OBJEXT)
	-rm -f src/passes/MergeKernels.$(OBJEXT)
	-rm -f src/passes/PrintDotDFG.$(OBJEXT)
	-rm -f src/passes/TaskExtraction.$(OBJEXT)
	-rm -f src/utils.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include src/$(DEPDIR)/AstToDfgVisitor.Po
include src/$(DEPDIR)/AstToMaxJVisitor.Po
include src/$(DEPDIR)/Design.Po
include src/$(DEPDIR)/DfeGraph.Po
include src/$(DEPDIR)/DfeTask.Po
include src/$(DEPDIR)/DfeTopSortVisitor.Po
include src/$(DEPDIR)/DotDFSVisitor.Po
include src/$(DEPDIR)/DotPrint.Po
include src/$(DEPDIR)/Kernel.Po
include src/$(DEPDIR)/Stencil.Po
include src/$(DEPDIR)/StencilAstToMaxJVisitor.Po
include src/$(DEPDIR)/StencilCodeGenerator.Po
include src/$(DEPDIR)/StencilOffset.Po
include src/$(DEPDIR)/main.Po
include src/$(DEPDIR)/utils.Po
include src/DataFlowGraph/$(DEPDIR)/BFSVisitor.Po
include src/DataFlowGraph/$(DEPDIR)/CounterNode.Po
include src/DataFlowGraph/$(DEPDIR)/DFSVisitor.Po
include src/DataFlowGraph/$(DEPDIR)/DataFlowGraph.Po
include src/DataFlowGraph/$(DEPDIR)/InputNode.Po
include src/DataFlowGraph/$(DEPDIR)/MuxNode.Po
include src/DataFlowGraph/$(DEPDIR)/Node.Po
include src/DataFlowGraph/$(DEPDIR)/OutputNode.Po
include src/DataFlowGraph/$(DEPDIR)/SinkNode.Po
include src/DataFlowGraph/$(DEPDIR)/SourceNode.Po
include src/DataFlowGraph/$(DEPDIR)/TopSortVisitor.Po
include src/highlevel/$(DEPDIR)/HLAVisitor.Po
include src/highlevel/$(DEPDIR)/HighlevelAnalysis.Po
include src/ife/$(DEPDIR)/IFEVisitor.Po
include src/ife/$(DEPDIR)/IdlefunctionElimination.Po
include src/passes/$(DEPDIR)/BuildDFG.Po
include src/passes/$(DEPDIR)/CodeGeneration.Po
include src/passes/$(DEPDIR)/ExtractStencil.Po
include src/passes/$(DEPDIR)/GenerateAnalysisOverview.Po
include src/passes/$(DEPDIR)/KernelExtraction.Po
include src/passes/$(DEPDIR)/KernelVisitor.Po
include src/passes/$(DEPDIR)/MergeKernels.Po
include src/passes/$(DEPDIR)/PrintDotDFG.Po
include src/passes/$(DEPDIR)/TaskExtraction.Po

.cc.o:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cc.obj:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cxx.o:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cxx.obj:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) $(SCRIPTS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f src/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/$(am__dirstamp)
	-rm -f src/DataFlowGraph/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/DataFlowGraph/$(am__dirstamp)
	-rm -f src/highlevel/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/highlevel/$(am__dirstamp)
	-rm -f src/ife/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/ife/$(am__dirstamp)
	-rm -f src/passes/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/passes/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf src/$(DEPDIR) src/DataFlowGraph/$(DEPDIR) src/highlevel/$(DEPDIR) src/ife/$(DEPDIR) src/passes/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf src/$(DEPDIR) src/DataFlowGraph/$(DEPDIR) src/highlevel/$(DEPDIR) src/ife/$(DEPDIR) src/passes/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic ctags dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-lzma dist-shar dist-tarZ dist-xz \
	dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags uninstall \
	uninstall-am uninstall-binPROGRAMS


test: all
	./tests.sh

test-remote: all
	REMOTE=true ./tests.sh

cscope:
	cscope -b -s src

run: 
	./fastc test/testApplications/maxc/RTM.c
	dot -Tps analysis_overview.dot > 1.ps
	evince 1.ps 
dot:
	dot -Tps do_forward_graph.dot > low_level.ps
	evince low_level.ps

.PHONY: test

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
